version: '3.9'

services:
  nextcloud:
    build: ./nextcloud
    ports:
      - "49153:80"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    env_file:
      - ./nextcloud.env
      - ./postgres.env
      - ./redis.env
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
    depends_on:
      - postgres
      - redis
    restart: always
    stop_signal: SIGTERM

  postgres:
    build: ./postgres
    env_file:
      - ./postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    stop_signal: SIGTERM

  redis:
    build: ./redis
    volumes:
      - redis:/data
    restart: always
    stop_signal: SIGTERM

volumes:
  nextcloud:
  nextcloud_config:
  nextcloud_data:
  postgres:
  redis:
