version: '3.8'

services:
  nextcloud:
    build: ./nextcloud
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - ./cache.env
      - ./database.env
      - ./nextcloud.env
    volumes:
      - html:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data
    depends_on:
      - database
      - cache
    restart: always

  webserver:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - html:/var/www/html:ro
    secrets:
      - source: fullchain
        target: fullchain.pem
      - source: privkey
        target: privkey.pem
    depends_on:
      - nextcloud
    restart: always

  database:
    build: ./postgres
    env_file:
      - ./database.env
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  cache:
    build: ./redis
    volumes:
      - cache:/data
    restart: always

volumes:
  cache:
  config:
  data:
  database:
  html:

secrets:
  fullchain:
    file: fullchain.pem
  privkey:
    file: privkey.pem
