version: '3.8'

services:
  app:
    build: ./nextcloud
    container_name: nextcloud-app
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=app
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost/status.php | jq -e .installed"]
    image: nextcloud-app
    ports:
      - "8080:80"
    restart: unless-stopped
    stop_signal: SIGWINCH
    volumes:
      - /cube_pool/nextcloud/app:/var/www/html
      - /cube_pool/nextcloud/config:/var/www/html/config
      - /cube_pool/nextcloud/data:/var/www/html/data

  cron:
    container_name: nextcloud-cron
    entrypoint: ["/cron.sh"]
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    volumes:
      - /cube_pool/nextcloud/app:/var/www/html
      - /cube_pool/nextcloud/config:/var/www/html/config
      - /cube_pool/nextcloud/data:/var/www/html/data

  hpb:
    container_name: nextcloud-hpb
    entrypoint: ["/hpb.sh"]
    depends_on:
      app:
        condition: service_healthy
    environment:
      - NEXTCLOUD_URL=http://app
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    image: nextcloud-app
    ports:
      - "7867:7867"
    restart: unless-stopped
    user: www-data
    volumes:
      - /cube_pool/nextcloud/app:/var/www/html
      - /cube_pool/nextcloud/config:/var/www/html/config
      - /cube_pool/nextcloud/data:/var/www/html/data

  cache:
    build: ./redis
    container_name: nextcloud-cache
    env_file:
      - ./cache.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    image: nextcloud-cache
    restart: unless-stopped

  db:
    build: ./postgres
    container_name: nextcloud-db
    env_file:
      - ./db.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
      interval: 5s
    image: nextcloud-db
    restart: unless-stopped
    volumes:
      - /cube_pool/nextcloud/postgres:/var/lib/postgresql/data

networks:
  default:
    name: nextcloud
