version: '3'

services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024G
    healthcheck:
      test: curl -sSf http://localhost/status.php | jq -e '(.installed==true) and (.maintenance==false)'
    hostname: app
    image: nextcloud-app
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
      - /pool-0/nextcloud/app:/var/www/html
      - /pool-0/nextcloud/config:/var/www/html/config
      - /pool-0/nextcloud/custom_apps:/var/www/html/custom_apps
      - /pool-0/nextcloud/data:/var/www/html/data

  cron:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/cron.sh"]
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes_from:
      - app

  notify_push:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/notify_push.sh"]
    environment:
      - NEXTCLOUD_URL=http://app
    image: nextcloud-app
    ports:
      - "52191:7867"
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  previewgenerator:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/previewgenerator.sh"]
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  imaginary:
    build: ./imaginary
    environment:
      - MALLOC_ARENA_MAX=2
    healthcheck:
      test: curl -sSf http://localhost:9000/health
    restart: unless-stopped

  cache:
    build: ./redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
      - REDIS_IO_THREADS=8
      - REDIS_IO_THREADS_DO_READS=yes
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  db:
    build: ./postgresql
    environment:
      - POSTGRESQL_DATABASE=nextcloud
      - POSTGRESQL_PASSWORD=nextcloud
      - POSTGRESQL_USERNAME=nextcloud
    healthcheck:
      test: pg_isready -U nextcloud || exit 1
    restart: unless-stopped
    volumes:
      - /pool-0/nextcloud/db:/bitnami/postgresql
    tmpfs:
      - /docker-entrypoint-preinitdb.d
      - /docker-entrypoint-initdb.d
