version: '3.7'

services:
  webserver:
    image: nextcloud:18.0-apache
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - database.env
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
    depends_on:
      - database
      - cache
    restart: always

  database:
    image: postgres:12.1-alpine
    env_file:
      - database.env
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:5.0-alpine
    volumes:
      - cache:/data
    restart: always

  proxy:
    image: haproxy:2.1-alpine
    ports:
      - "443:443"
    volumes:
      - ./combined.pem:/usr/local/etc/haproxy/combined.pem:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - webserver
    restart: always

volumes:
  cache:
  database:
  nextcloud:
  nextcloud_config:
  nextcloud_data:
