version: '3.9'

services:
  app:
    build: ./nextcloud
    container_name: nextcloud-app
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - ./nextcloud.env
      - ./postgres.env
      - ./redis.env
    ports:
      - "80:80"
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./local/nextcloud/app:/var/www/html
      - ./local/nextcloud/config:/var/www/html/config
      - ./local/nextcloud/data:/var/www/html/data

  database:
    build: ./postgres
    container_name: nextcloud-database
    env_file:
      - ./postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
      interval: 5s
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./local/nextcloud/postgres:/var/lib/postgresql/data

  cache:
    build: ./redis
    container_name: nextcloud-cache
    restart: always
    stop_signal: SIGTERM
