version: '3'

services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=app # Append your domain here
      - TRUSTED_PROXIES=172.16.0.0/12
    env_file:
      - ./nextcloud.env
    healthcheck:
      test: curl -sSf http://localhost/status.php | jq -e '(.installed==true) and (.maintenance==false)'
    hostname: app
    image: nextcloud-app
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /pool-1/nc-app:/var/www/html
      - /pool-1/nc-config:/var/www/html/config
      - /pool-0/nc-data:/var/www/html/data

  cron:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/cron.sh"]
    env_file:
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes_from:
      - app

  notify_push:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/notify_push.sh"]
    env_file:
      - ./nextcloud.env
    environment:
      - NEXTCLOUD_URL=http://app
    image: nextcloud-app
    ports:
      - "52191:7867"
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  previewgenerator:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/previewgenerator.sh"]
    env_file:
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  imaginary:
    build: ./imaginary
    environment:
      - MALLOC_ARENA_MAX=2
    healthcheck:
      test: curl -sSf http://localhost:9000/health
    restart: unless-stopped

  cache:
    image: bitnami/redis:7.2
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_IO_THREADS=4
      - REDIS_PASSWORD=nextcloud
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  db:
    image: bitnami/postgresql:16
    environment:
      - POSTGRESQL_DATABASE=nextcloud
      - POSTGRESQL_PASSWORD=nextcloud
      - POSTGRESQL_USERNAME=nextcloud
    healthcheck:
      test: pg_isready -U nextcloud || exit 1
    restart: unless-stopped
    volumes:
      - /pool-1/nc-db:/bitnami/postgresql
    tmpfs:
      - /docker-entrypoint-preinitdb.d
      - /docker-entrypoint-initdb.d
