version: '3.9'

services:
  app:
    container_name: nextcloud-app
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - ./nextcloud.env
      - ./postgres.env
      - ./redis.env
    ports:
      - "49153:80"
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - ./volumes/nextcloud_config:/var/www/html/config
      - ./volumes/nextcloud_data:/var/www/html/data

  database:
    container_name: nextcloud-database
    build: ./postgres
    env_file:
      - ./postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
      interval: 5s
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  cache:
    build: ./redis
    container_name: nextcloud-cache
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./volumes/redis:/data
