version: '3.9'

services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=webserver # Append your domain here
      - TRUSTED_PROXIES=172.16.0.0/12
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    hostname: app
    image: nextcloud-app
    restart: unless-stopped
    volumes:
      - app:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data

  cron:
    depends_on:
      app:
        condition: service_started
    entrypoint: ["/cron.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - app:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data

  hpb:
    depends_on:
      app:
        condition: service_started
      webserver:
        condition: service_started
    entrypoint: ["/hpb.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    environment:
      - NEXTCLOUD_URL=http://webserver
      - PORT=52191
    image: nextcloud-app
    ports:
      - "52191:52191"
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes:
      - app:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data

  webserver:
    build: ./nginx
    depends_on:
      app:
        condition: service_started
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
      - app:/var/www/html:ro

  cache:
    build: ./redis
    env_file:
      - ./cache.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    restart: unless-stopped
    volumes:
      - cache:/data

  db:
    build: ./postgres
    env_file:
      - ./db.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
      interval: 5s
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  app:
  cache:
  config:
  data:
  db:
