version: '3.8'

services:
  nextcloud:
    build: ./nextcloud
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - ./cache.env
      - ./database.env
      - ./nextcloud.env
    volumes:
      - html:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data
    depends_on:
      - database
      - cache
    restart: always

  database:
    build: ./postgres
    env_file:
      - ./database.env
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  cache:
    build: ./redis
    tmpfs: /data
    restart: always

volumes:
  config:
  data:
  database:
  html:
