version: '3.9'

services:
  app:
    build: ./nextcloud
    container_name: nextcloud-app
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - ./nextcloud.env
      - ./postgres.env
      - ./redis.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 5s
    ports:
      - "80:80"
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./local/nextcloud/html:/var/www/html
      - ./local/nextcloud/config:/var/www/html/config
      - ./local/nextcloud/data:/var/www/html/data

  hpb:
    image: nextcloud-compose_app
    container_name: nextcloud-hpb
    depends_on:
      app:
        condition: service_healthy
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
    entrypoint: /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push /var/www/html/config/config.php
    environment:
      - PORT=7867
      - NEXTCLOUD_URL=http://app
    ports:
      - "7867:7867"
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./local/nextcloud/html:/var/www/html
      - ./local/nextcloud/config:/var/www/html/config
      - ./local/nextcloud/data:/var/www/html/data

  database:
    build: ./postgres
    container_name: nextcloud-database
    env_file:
      - ./postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nextcloud"]
      interval: 5s
    restart: always
    stop_signal: SIGTERM
    volumes:
      - ./local/nextcloud/postgres:/var/lib/postgresql/data

  cache:
    build: ./redis
    container_name: nextcloud-cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    restart: always
    stop_signal: SIGTERM
