version: '3'

services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=app # Append your domain here
      - TRUSTED_PROXIES=172.16.0.0/12
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    hostname: app
    image: nextcloud-app
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /pool-1/nc-app:/var/www/html
      - /pool-1/nc-config:/var/www/html/config
      - /pool-1/nc-data:/var/www/html/data

  cron:
    depends_on:
      app:
        condition: service_started
    entrypoint: ["/cron.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes_from:
      - app

  notify_push:
    depends_on:
      app:
        condition: service_started
    entrypoint: ["/notify_push.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    environment:
      - NEXTCLOUD_URL=http://app
    image: nextcloud-app
    ports:
      - "52191:7867"
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  previewgenerator:
    depends_on:
      app:
        condition: service_started
    entrypoint: ["/previewgenerator.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  imaginary:
    build: ./imaginary
    environment:
      - MALLOC_ARENA_MAX=2
    healthcheck:
      test: curl -f 127.0.0.1:9000/health
    restart: unless-stopped

  cache:
    build: ./redis
    env_file:
      - ./cache.env
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    tmpfs:
      - /data

  db:
    build: ./postgres
    env_file:
      - ./db.env
    healthcheck:
      test: pg_isready -U nextcloud || exit 1
    restart: unless-stopped
    volumes:
      - /pool-1/nc-db:/var/lib/postgresql/data
