version: '3.8'

services:
  nextcloud:
    image: nextcloud:19.0.1-fpm-alpine
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=cache
    env_file:
      - cache.env
      - database.env
      - nextcloud.env
    volumes:
      - ./html:/var/www/html
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    depends_on:
      - database
      - cache

  webserver:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html:ro
    secrets:
      - source: fullchain
        target: fullchain.pem
      - source: privkey
        target: privkey.pem
    depends_on:
      - nextcloud

  database:
    image: postgres:12.3-alpine
    env_file:
      - database.env
    volumes:
      - ./database:/var/lib/postgresql/data

  cache:
    build: ./redis
    privileged: true
    volumes:
      - cache:/data

volumes:
  cache:

secrets:
  fullchain:
    file: fullchain.pem
  privkey:
    file: privkey.pem
